import { countUncompletedTasks } from '@admin/tasks';
import { countPendingDocumentsForReview } from '@admissions/documents/_server/actions';
import { countPendingPaymentsForReview } from '@admissions/payments/_server/actions';
import { countPendingGraduationClearances } from '@registry/graduation';
import { countPendingStudentStatuses } from '@registry/student-statuses';
import {
	IconActivity,
	IconBell,
	IconBook,
	IconBook2,
	IconBooks,
	IconBuildingBank,
	IconBuildingCommunity,
	IconCalculator,
	IconCalendar,
	IconCalendarDue,
	IconCalendarEvent,
	IconCash,
	IconCategory,
	IconCertificate,
	IconChartBar,
	IconChecklist,
	IconClipboardCheck,
	IconClipboardData,
	IconClipboardList,
	IconCreditCard,
	IconDeviceDesktopAnalytics,
	IconDoor,
	IconEye,
	IconFileAnalytics,
	IconFileExport,
	IconFileSearch,
	IconFileText,
	IconFlask,
	IconGavel,
	IconInbox,
	IconLayoutGrid,
	IconLibrary,
	IconListCheck,
	IconMail,
	IconMailSpark,
	IconMapPin,
	IconMessageQuestion,
	IconMessageStar,
	IconNote,
	IconPackage,
	IconPresentation,
	IconPrinter,
	IconReportAnalytics,
	IconRobot,
	IconSchool,
	IconSearch,
	IconSend,
	IconSettings,
	IconShield,
	IconSparkles,
	IconStack2,
	IconTags,
	IconTemplate,
	IconUserCheck,
	IconUserExclamation,
	IconUserOff,
	IconUserPlus,
	IconUserShield,
	IconUsers,
	IconUsersGroup,
	IconWriting,
} from '@tabler/icons-react';
import { createElement } from 'react';
import type { Session } from '@/core/auth';
import { hasAnyPermission } from '@/core/auth/sessionPermissions';
import type { NavItem } from '../types';
import { FiveDaysLabel } from './FiveDaysLabel';

function isTimetableEditor(session: Session | null) {
	return hasAnyPermission(session, 'timetable', ['create', 'update', 'delete']);
}

export const adminNav: NavItem[] = [
	{
		label: 'Students',
		group: 'Registry',
		href: '/registry/students',
		icon: IconUsers,
		permissions: [{ resource: 'students', action: 'read' }],
	},
	{
		label: 'Registration',
		group: 'Registry',
		href: '/registry/registration/requests',
		icon: IconUserPlus,
		permissions: [{ resource: 'registration', action: 'read' }],
	},
	{
		label: 'Auto-Approvals',
		group: 'Registry',
		href: '/registry/clearance/auto-approve',
		icon: IconRobot,
		permissions: [{ resource: 'auto-approvals', action: 'read' }],
	},
	{
		label: 'Graduations',
		group: 'Registry',
		icon: IconSchool,
		collapsed: false,
		permissions: [{ resource: 'graduation', action: 'read' }],
		children: [
			{
				label: 'Requests',
				href: '/registry/graduation/requests',
				icon: IconCertificate,
			},
			{
				label: 'Dates',
				href: '/registry/graduation/dates',
				icon: IconCalendarEvent,
			},
			{
				label: 'Certificate Reprints',
				href: '/registry/certificate-reprints',
				icon: IconPrinter,
				permissions: [{ resource: 'certificate-reprints', action: 'read' }],
			},
		],
	},
	{
		label: 'Graduation Clearance',
		group: 'Registry',
		href: '/registry/graduation/clearance',
		icon: IconCertificate,
		permissions: [{ resource: 'graduation-clearance', action: 'read' }],
		notificationCount: {
			queryKey: ['graduation-clearances', 'pending'],
			queryFn: () => countPendingGraduationClearances(),
			color: 'red',
		},
	},
	{
		label: 'Student Status',
		group: 'Registry',
		href: '/registry/student-statuses',
		icon: IconUserExclamation,
		permissions: [{ resource: 'student-statuses', action: 'read' }],
		notificationCount: {
			queryKey: ['student-statuses', 'pending'],
			queryFn: () => countPendingStudentStatuses(),
			color: 'red',
		},
	},
	{
		label: 'Notes',
		group: 'Registry',
		href: '/registry/student-notes',
		description: 'Notes on Students',
		icon: IconNote,
		permissions: [{ resource: 'student-notes', action: 'read' }],
	},
	{
		label: 'Letters',
		group: 'Registry',
		icon: IconMail,
		collapsed: false,
		children: [
			{
				label: 'Letters',
				href: '/registry/letters/generate',
				icon: IconMailSpark,
				permissions: [{ resource: 'letters', action: 'read' }],
			},
			{
				label: 'Templates',
				href: '/registry/letters/templates',
				icon: IconTemplate,
				permissions: [{ resource: 'letter-templates', action: 'read' }],
			},
		],
	},
	{
		label: 'Blocked Students',
		group: 'Registry',
		href: '/registry/blocked-students',
		icon: IconUserOff,
		permissions: [{ resource: 'blocked-students', action: 'read' }],
	},
	{
		label: 'Terms',
		group: 'Registry',
		href: '/registry/terms',
		icon: IconCalendarDue,
		permissions: [{ resource: 'terms-settings', action: 'read' }],
	},
	{
		label: 'Tasks',
		group: 'Admin',
		href: '/admin/tasks',
		icon: IconChecklist,
		permissions: [{ resource: 'tasks', action: 'read' }],
		notificationCount: {
			queryKey: ['tasks', 'uncompleted'],
			queryFn: () => countUncompletedTasks(),
			color: 'red',
		},
	},
	{
		label: 'Users',
		group: 'Admin',
		href: '/admin/users',
		icon: IconUserShield,
		permissions: [{ resource: 'users', action: 'read' }],
	},
	{
		label: 'Permission Presets',
		group: 'Admin',
		href: '/admin/permission-presets',
		icon: IconShield,
		permissions: [{ resource: 'permission-presets', action: 'read' }],
	},
	{
		label: 'Notifications',
		group: 'Admin',
		href: '/admin/notifications',
		icon: IconBell,
		permissions: [{ resource: 'notifications', action: 'read' }],
	},
	{
		label: 'Activity Tracker',
		group: 'Admin',
		href: '/admin/activity-tracker',
		icon: IconActivity,
		permissions: [{ resource: 'activity-tracker', action: 'read' }],
	},
	{
		label: 'Tools',
		group: 'Admin',
		icon: IconSettings,
		collapsed: false,
		children: [
			{
				label: 'Simulator',
				href: '/admin/tools/simulate',
				icon: IconFlask,
			},
			{
				label: 'Grade Calculator',
				href: '/admin/tools/grade-calculator',
				icon: IconCalculator,
			},
			{
				label: 'Grade Finder',
				href: '/admin/tools/grade-finder',
				icon: IconSearch,
			},
			{
				label: 'Document Analyzer',
				href: '/admin/tools/document-analyzer',
				icon: IconFileSearch,
			},
			{
				label: 'AI Query',
				href: '/admin/tools/query',
				icon: IconSparkles,
				roles: ['admin'],
			},
		] as NavItem[],
	},
	{
		label: 'Bulk',
		group: 'Admin',
		icon: IconPackage,
		children: [
			{
				label: 'Export Transcript',
				href: '/admin/bulk/transcripts',
				icon: IconFileExport,
			},
		] as NavItem[],
	},
	{
		label: 'Lecturers',
		group: 'Academic',
		description: 'Assigned Modules',
		href: '/academic/lecturers',
		icon: IconPresentation,
		permissions: [{ resource: 'lecturers', action: 'read' }],
	},
	{
		label: 'Assessments',
		group: 'Academic',
		href: '/academic/assessments',
		icon: IconListCheck,
		permissions: [{ resource: 'assessments', action: 'read' }],
	},
	{
		label: 'Attendance',
		group: 'Academic',
		href: '/academic/attendance',
		icon: IconCalendarEvent,
		permissions: [{ resource: 'attendance', action: 'read' }],
	},
	{
		label: 'Gradebook',
		group: 'Academic',
		icon: IconClipboardData,
		collapsed: false,
		children: [],
		permissions: [{ resource: 'gradebook', action: 'read' }],
	},
	{
		label: 'Modules',
		group: 'Academic',
		href: '/academic/modules',
		icon: IconBook,
		permissions: [{ resource: 'modules', action: 'read' }],
	},
	{
		label: 'Semester Modules',
		group: 'Academic',
		href: '/academic/semester-modules',
		icon: IconBooks,
		permissions: [{ resource: 'semester-modules', action: 'read' }],
	},
	{
		label: 'Schools',
		group: 'Academic',
		href: '/academic/schools',
		icon: IconSchool,
		permissions: [{ resource: 'school-structures', action: 'read' }],
	},
	{
		label: createElement(FiveDaysLabel),
		group: 'Academic',
		description: 'Learning Management System',
		icon: IconDeviceDesktopAnalytics,
		href: '/lms/courses',
		permissions: [{ resource: 'assigned-modules', action: 'read' }],
	},
	{
		label: 'Timetable',
		group: 'Academic',
		icon: IconCalendar,
		collapsed: false,
		children: [
			{
				label: 'Viewer',
				icon: IconCalendar,
				href: '/timetable/viewer',
				permissions: [{ resource: 'timetable', action: 'read' }],
			},
			{
				label: 'Allocations',
				icon: IconLayoutGrid,
				href: '/timetable/timetable-allocations',
				isVisible: isTimetableEditor,
			},
			{
				label: 'Venues',
				icon: IconDoor,
				href: '/timetable/venues',
				permissions: [{ resource: 'venues', action: 'read' }],
			},
			{
				label: 'Venue Types',
				icon: IconTags,
				href: '/timetable/venue-types',
				permissions: [{ resource: 'venues', action: 'read' }],
			},
		],
	},
	{
		label: 'Sponsors',
		group: 'Finance',
		href: '/finance/sponsors',
		icon: IconBuildingBank,
		permissions: [{ resource: 'sponsors', action: 'read' }],
	},
	{
		label: 'Applicants',
		group: 'Admissions',
		href: '/admissions/applicants',
		icon: IconUsers,
		permissions: [{ resource: 'applicants', action: 'read' }],
	},
	{
		label: 'Applications',
		group: 'Admissions',
		href: '/admissions/applications',
		icon: IconClipboardList,
		permissions: [{ resource: 'applications', action: 'read' }],
	},
	{
		label: 'Admissions Payments',
		group: 'Admissions',
		href: '/admissions/payments',
		icon: IconCreditCard,
		permissions: [{ resource: 'admissions-payments', action: 'read' }],
		notificationCount: {
			queryKey: ['payments', 'pending-review-count'],
			queryFn: countPendingPaymentsForReview,
			color: 'red',
		},
	},
	{
		label: 'Document Review',
		group: 'Admissions',
		href: '/admissions/documents',
		icon: IconFileSearch,
		permissions: [{ resource: 'admissions-documents', action: 'read' }],
		notificationCount: {
			queryKey: ['documents', 'pending-review-count'],
			queryFn: countPendingDocumentsForReview,
			color: 'red',
		},
	},
	{
		label: 'Admissions Settings',
		group: 'Admissions',
		icon: IconSettings,
		collapsed: false,
		children: [
			{
				label: 'Intake Periods',
				href: '/admissions/intake-periods',
				icon: IconCalendarEvent,
				permissions: [{ resource: 'intake-periods', action: 'read' }],
			},
			{
				label: 'Certificate Types',
				href: '/admissions/certificate-types',
				icon: IconCertificate,
				permissions: [{ resource: 'certificate-types', action: 'read' }],
			},
			{
				label: 'Subjects',
				href: '/admissions/subjects',
				icon: IconBook,
				permissions: [{ resource: 'subjects', action: 'read' }],
			},
			{
				label: 'Recognized Schools',
				href: '/admissions/recognized-schools',
				icon: IconBuildingCommunity,
				permissions: [{ resource: 'recognized-schools', action: 'read' }],
			},
			{
				label: 'Entry Requirements',
				href: '/admissions/entry-requirements',
				icon: IconChecklist,
				permissions: [{ resource: 'entry-requirements', action: 'read' }],
			},
		] as NavItem[],
	},
	{
		label: 'Reports',
		icon: IconReportAnalytics,
		group: 'Admissions',
		collapsed: false,
		permissions: [{ resource: 'applications', action: 'read' }],
		children: [
			{
				label: 'Application Summary',
				href: '/admissions/reports/application-summary',
				icon: IconFileAnalytics,
			},
			{
				label: 'Demographics',
				href: '/admissions/reports/demographics',
				icon: IconUsersGroup,
			},
			{
				label: 'Geographic',
				href: '/admissions/reports/geographic',
				icon: IconMapPin,
			},
			{
				label: 'Program Demand',
				href: '/admissions/reports/program-demand',
				icon: IconChartBar,
			},
			{
				label: 'Academic Qualifications',
				href: '/admissions/reports/academic-qualifications',
				icon: IconSchool,
			},
		],
	},
	{
		label: 'Employees',
		group: 'Human Resource',
		href: '/human-resource/employees',
		icon: IconUsers,
		permissions: [{ resource: 'employees', action: 'read' }],
	},
	{
		label: 'Appraisals',
		group: 'Human Resource',
		icon: IconClipboardData,
		collapsed: false,
		children: [
			{
				label: 'Cycles',
				href: '/appraisals/cycles',
				icon: IconCalendarEvent,
				permissions: [{ resource: 'feedback-cycles', action: 'read' }],
			},
			{
				label: 'Reports',
				href: '/appraisals/reports',
				icon: IconChartBar,
				permissions: [
					{ resource: 'student-feedback-reports', action: 'read' },
					{ resource: 'teaching-observation-reports', action: 'read' },
				],
			},
			{
				label: 'Student Feedback',
				icon: IconMessageStar,
				collapsed: false,
				children: [
					{
						label: 'Questions',
						href: '/appraisals/student-feedback/questions',
						icon: IconMessageQuestion,
						permissions: [
							{ resource: 'student-feedback-questions', action: 'read' },
						],
					},
				],
			},
			{
				label: 'Teaching Observation',
				icon: IconEye,
				collapsed: false,
				children: [
					{
						label: 'Criteria',
						href: '/appraisals/observation-criteria',
						icon: IconListCheck,
						permissions: [
							{ resource: 'teaching-observation-criteria', action: 'read' },
						],
					},
					{
						label: 'Observations',
						href: '/appraisals/teaching-observations',
						icon: IconClipboardCheck,
						permissions: [
							{ resource: 'teaching-observations', action: 'read' },
						],
					},
				],
			},
		],
	},
	{
		label: 'Library',
		group: 'Library',
		icon: IconLibrary,
		collapsed: false,
		permissions: [{ resource: 'library', action: 'read' }],
		children: [
			{
				label: 'Catalog',
				href: '/library/catalog',
				icon: IconBooks,
			},
			{
				label: 'Books',
				href: '/library/books',
				icon: IconBook2,
			},
			{
				label: 'Loans',
				href: '/library/loans',
				icon: IconLibrary,
			},
			{
				label: 'Authors',
				href: '/library/authors',
				icon: IconUsers,
			},
			{
				label: 'Categories',
				href: '/library/categories',
				icon: IconCategory,
			},
			{
				label: 'Fines',
				href: '/library/fines',
				icon: IconCash,
			},
			{
				label: 'Resources',
				icon: IconTags,
				collapsed: false,
				children: [
					{
						label: 'Publications',
						href: '/library/resources/publications',
						icon: IconWriting,
					},
					{
						label: 'Question Papers',
						href: '/library/resources/question-papers',
						icon: IconFileText,
					},
				],
			},
			{
				label: 'Settings',
				href: '/library/settings',
				icon: IconSettings,
			},
		],
	},
	{
		label: 'Reports',
		group: 'Analytics',
		icon: IconReportAnalytics,
		collapsed: false,
		children: [
			{
				label: 'Course Summary',
				href: '/reports/academic/course-summary',
				icon: IconReportAnalytics,
				permissions: [{ resource: 'reports-course-summary', action: 'read' }],
			},
			{
				label: 'Attendance',
				href: '/reports/academic/attendance',
				icon: IconReportAnalytics,
				permissions: [{ resource: 'reports-attendance', action: 'read' }],
			},
			{
				label: 'Board of Examination',
				href: '/reports/academic/boe',
				icon: IconGavel,
				permissions: [{ resource: 'reports-boe', action: 'read' }],
			},
			{
				label: 'Student Enrollments',
				href: '/reports/registry/student-enrollments',
				icon: IconReportAnalytics,
				permissions: [{ resource: 'reports-enrollments', action: 'read' }],
			},
			{
				label: 'Graduations',
				href: '/reports/registry/graduations',
				icon: IconSchool,
				permissions: [{ resource: 'reports-graduation', action: 'read' }],
			},
			{
				label: 'Sponsored Students',
				href: '/reports/finance/sponsored-students',
				icon: IconReportAnalytics,
				permissions: [
					{ resource: 'reports-sponsored-students', action: 'read' },
				],
			},
		],
	},
	{
		label: 'Mail',
		group: 'Mail',
		icon: IconMail,
		collapsed: false,
		children: [
			{
				label: 'Inbox',
				href: '/mail/inbox',
				icon: IconInbox,
				permissions: [{ resource: 'mails', action: 'read' }],
			},
			{
				label: 'Accounts',
				href: '/mail/accounts',
				icon: IconUserCheck,
				permissions: [{ resource: 'mails', action: 'read' }],
			},
			{
				label: 'Sent',
				href: '/mail/sent',
				icon: IconSend,
				permissions: [{ resource: 'mails', action: 'read' }],
			},
			{
				label: 'Queue',
				href: '/mail/queue',
				icon: IconStack2,
				permissions: [{ resource: 'mails', action: 'read' }],
			},
			{
				label: 'Templates',
				href: '/mail/templates',
				icon: IconTemplate,
				permissions: [{ resource: 'mails', action: 'read' }],
			},
			{
				label: 'Settings',
				href: '/mail/settings',
				icon: IconSettings,
				permissions: [{ resource: 'mails', action: 'read' }],
			},
		],
	},
];
