import {
	IconActivity,
	IconBell,
	IconBook,
	IconBooks,
	IconBuildingBank,
	IconCalendarDue,
	IconCalendarEvent,
	IconCertificate,
	IconChecklist,
	IconClipboardCheck,
	IconDoor,
	IconInbox,
	IconNote,
	IconPrinter,
	IconReportAnalytics,
	IconSchool,
	IconSend,
	IconTags,
	IconUserCheck,
	IconUserExclamation,
	IconUserOff,
	IconUserPlus,
	IconUsers,
} from '@tabler/icons-react';
import { countPendingGraduationClearances } from '@/app/registry/graduation';
import { countPendingClearances } from '@/app/registry/registration';
import { countPendingStudentStatuses } from '@/app/registry/student-statuses';
import type { NavItem } from '../module-config.types';

export const registryNav: NavItem[] = [
	{
		label: 'Students',
		href: '/registry/students',
		icon: IconUsers,
		permissions: [{ resource: 'students', action: 'read' }],
	},
	{
		label: 'Registration',
		href: '/registry/registration/requests',
		icon: IconUserPlus,
		permissions: [{ resource: 'registration', action: 'read' }],
	},
	{
		label: 'Registration Clearance',
		href: '/registry/registration/clearance',
		icon: IconClipboardCheck,
		permissions: [{ resource: 'registration-clearance', action: 'read' }],
		notificationCount: {
			queryKey: ['clearances', 'pending'],
			queryFn: () => countPendingClearances(),
			color: 'red',
		},
	},
	{
		label: 'Graduations',
		icon: IconSchool,
		collapsed: true,
		permissions: [{ resource: 'graduation', action: 'read' }],
		children: [
			{
				label: 'Requests',
				href: '/registry/graduation/requests',
				icon: IconCertificate,
			},
			{
				label: 'Dates',
				href: '/registry/graduation/dates',
				icon: IconCalendarEvent,
			},
			{
				label: 'Certificate Reprints',
				href: '/registry/certificate-reprints',
				icon: IconPrinter,
				permissions: [{ resource: 'certificate-reprints', action: 'read' }],
			},
		],
	},
	{
		label: 'Student Status',
		href: '/registry/student-statuses',
		icon: IconUserExclamation,
		permissions: [{ resource: 'student-statuses', action: 'read' }],
		notificationCount: {
			queryKey: ['student-statuses', 'pending'],
			queryFn: () => countPendingStudentStatuses(),
			color: 'red',
		},
	},
	{
		label: 'Notes',
		href: '/registry/student-notes',
		icon: IconNote,
		permissions: [{ resource: 'student-notes', action: 'read' }],
	},
	{
		label: 'Blocked Students',
		href: '/registry/blocked-students',
		icon: IconUserOff,
		permissions: [{ resource: 'blocked-students', action: 'read' }],
	},
	{
		label: 'Terms',
		href: '/registry/terms',
		icon: IconCalendarDue,
		permissions: [{ resource: 'terms-settings', action: 'read' }],
	},
	{
		label: 'Modules',
		href: '/academic/modules',
		icon: IconBook,
		permissions: [{ resource: 'modules', action: 'create' }],
	},
	{
		label: 'Semester Modules',
		href: '/academic/semester-modules',
		icon: IconBooks,
		permissions: [{ resource: 'semester-modules', action: 'create' }],
	},
	{
		label: 'Schools',
		href: '/academic/schools',
		icon: IconSchool,
		permissions: [{ resource: 'school-structures', action: 'update' }],
	},
	{
		label: 'Venues',
		icon: IconDoor,
		href: '/timetable/venues',
		permissions: [{ resource: 'venues', action: 'create' }],
	},
	{
		label: 'Venue Types',
		icon: IconTags,
		href: '/timetable/venue-types',
		permissions: [{ resource: 'venues', action: 'create' }],
	},
	{
		label: 'Sponsors',
		href: '/finance/sponsors',
		icon: IconBuildingBank,
		permissions: [{ resource: 'sponsors', action: 'read' }],
	},
	{
		label: 'Graduation Clearance',
		href: '/registry/graduation/clearance',
		icon: IconCertificate,
		permissions: [{ resource: 'graduation-clearance', action: 'read' }],
		notificationCount: {
			queryKey: ['graduation-clearances', 'pending'],
			queryFn: () => countPendingGraduationClearances(),
			color: 'red',
		},
	},
	{
		label: 'Attendance Report',
		href: '/reports/academic/attendance',
		icon: IconReportAnalytics,
		permissions: [{ resource: 'reports-attendance', action: 'read' }],
	},
	{
		label: 'Student Enrollments',
		href: '/reports/registry/student-enrollments',
		icon: IconReportAnalytics,
		permissions: [{ resource: 'reports-enrollments', action: 'read' }],
	},
	{
		label: 'Graduation Reports',
		href: '/reports/registry/graduations',
		icon: IconSchool,
		permissions: [{ resource: 'reports-graduation', action: 'read' }],
	},
	{
		label: 'Tasks',
		href: '/admin/tasks',
		icon: IconChecklist,
		permissions: [{ resource: 'tasks', action: 'read' }],
	},
	{
		label: 'Activity Tracker',
		href: '/admin/activity-tracker',
		icon: IconActivity,
		permissions: [{ resource: 'activity-tracker', action: 'read' }],
	},
	{
		label: 'Notifications',
		href: '/admin/notifications',
		icon: IconBell,
		permissions: [{ resource: 'notifications', action: 'read' }],
	},
	{
		label: 'Inbox',
		href: '/mail/inbox',
		icon: IconInbox,
		permissions: [{ resource: 'mails', action: 'read' }],
	},
	{
		label: 'Accounts',
		href: '/mail/accounts',
		icon: IconUserCheck,
		permissions: [{ resource: 'mails', action: 'read' }],
	},
	{
		label: 'Sent',
		href: '/mail/sent',
		icon: IconSend,
		permissions: [{ resource: 'mails', action: 'read' }],
	},
];
