DROP INDEX "blocked_students_std_no_idx";--> statement-breakpoint
DROP INDEX "task_assignments_user_id_idx";--> statement-breakpoint
ALTER TABLE "semester_modules" ALTER COLUMN "module_id" SET NOT NULL;--> statement-breakpoint
CREATE INDEX "fk_assessment_marks_assessment_id" ON "assessment_marks" USING btree ("assessment_id");--> statement-breakpoint
CREATE INDEX "fk_assessment_marks_std_no" ON "assessment_marks" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "idx_assessment_marks_assessment_id_std_no" ON "assessment_marks" USING btree ("assessment_id","std_no");--> statement-breakpoint
CREATE INDEX "fk_assessment_marks_audit_assessment_mark_id" ON "assessment_marks_audit" USING btree ("assessment_mark_id");--> statement-breakpoint
CREATE INDEX "fk_assessment_marks_audit_created_by" ON "assessment_marks_audit" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "fk_assessments_module_id" ON "assessments" USING btree ("module_id");--> statement-breakpoint
CREATE INDEX "fk_assessments_term_id" ON "assessments" USING btree ("term_id");--> statement-breakpoint
CREATE INDEX "fk_assessments_audit_assessment_id" ON "assessments_audit" USING btree ("assessment_id");--> statement-breakpoint
CREATE INDEX "fk_assessments_audit_created_by" ON "assessments_audit" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "fk_assigned_modules_user_id" ON "assigned_modules" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "fk_assigned_modules_term_id" ON "assigned_modules" USING btree ("term_id");--> statement-breakpoint
CREATE INDEX "fk_assigned_modules_semester_module_id" ON "assigned_modules" USING btree ("semester_module_id");--> statement-breakpoint
CREATE INDEX "fk_blocked_students_std_no" ON "blocked_students" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "idx_clearance_department" ON "clearance" USING btree ("department");--> statement-breakpoint
CREATE INDEX "idx_clearance_status" ON "clearance" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fk_clearance_audit_clearance_id" ON "clearance_audit" USING btree ("clearance_id");--> statement-breakpoint
CREATE INDEX "fk_clearance_audit_created_by" ON "clearance_audit" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "fk_documents_std_no" ON "documents" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "fk_fortinet_registrations_std_no" ON "fortinet_registrations" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "fk_fortinet_registrations_school_id" ON "fortinet_registrations" USING btree ("school_id");--> statement-breakpoint
CREATE INDEX "idx_fortinet_registrations_status" ON "fortinet_registrations" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fk_graduation_clearance_graduation_request_id" ON "graduation_clearance" USING btree ("graduation_request_id");--> statement-breakpoint
CREATE INDEX "fk_graduation_clearance_clearance_id" ON "graduation_clearance" USING btree ("clearance_id");--> statement-breakpoint
CREATE INDEX "fk_graduation_requests_student_program_id" ON "graduation_requests" USING btree ("student_program_id");--> statement-breakpoint
CREATE INDEX "fk_payment_receipts_graduation_request_id" ON "payment_receipts" USING btree ("graduation_request_id");--> statement-breakpoint
CREATE INDEX "fk_programs_school_id" ON "programs" USING btree ("school_id");--> statement-breakpoint
CREATE INDEX "fk_registration_clearance_registration_request_id" ON "registration_clearance" USING btree ("registration_request_id");--> statement-breakpoint
CREATE INDEX "fk_registration_clearance_clearance_id" ON "registration_clearance" USING btree ("clearance_id");--> statement-breakpoint
CREATE INDEX "fk_registration_requests_std_no" ON "registration_requests" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "fk_registration_requests_term_id" ON "registration_requests" USING btree ("term_id");--> statement-breakpoint
CREATE INDEX "idx_registration_requests_status" ON "registration_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fk_registration_requests_sponsor_id" ON "registration_requests" USING btree ("sponsor_id");--> statement-breakpoint
CREATE INDEX "fk_requested_modules_registration_request_id" ON "requested_modules" USING btree ("registration_request_id");--> statement-breakpoint
CREATE INDEX "fk_requested_modules_semester_module_id" ON "requested_modules" USING btree ("semester_module_id");--> statement-breakpoint
CREATE INDEX "fk_semester_modules_module_id" ON "semester_modules" USING btree ("module_id");--> statement-breakpoint
CREATE INDEX "fk_semester_modules_semester_id" ON "semester_modules" USING btree ("semester_id");--> statement-breakpoint
CREATE INDEX "idx_signups_status" ON "signups" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fk_signups_user_id" ON "signups" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "fk_sponsored_students_sponsor_id" ON "sponsored_students" USING btree ("sponsor_id");--> statement-breakpoint
CREATE INDEX "fk_sponsored_students_std_no" ON "sponsored_students" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "fk_sponsored_terms_sponsored_student_id" ON "sponsored_terms" USING btree ("sponsored_student_id");--> statement-breakpoint
CREATE INDEX "fk_sponsored_terms_term_id" ON "sponsored_terms" USING btree ("term_id");--> statement-breakpoint
CREATE INDEX "fk_statement_of_results_prints_std_no" ON "statement_of_results_prints" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "fk_statement_of_results_prints_printed_by" ON "statement_of_results_prints" USING btree ("printed_by");--> statement-breakpoint
CREATE INDEX "fk_structures_program_id" ON "structures" USING btree ("program_id");--> statement-breakpoint
CREATE INDEX "fk_student_card_prints_std_no" ON "student_card_prints" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "fk_student_card_prints_printed_by" ON "student_card_prints" USING btree ("printed_by");--> statement-breakpoint
CREATE INDEX "fk_student_modules_student_semester_id" ON "student_modules" USING btree ("student_semester_id");--> statement-breakpoint
CREATE INDEX "fk_student_modules_semester_module_id" ON "student_modules" USING btree ("semester_module_id");--> statement-breakpoint
CREATE INDEX "idx_student_modules_status" ON "student_modules" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fk_student_programs_std_no" ON "student_programs" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "idx_student_programs_status" ON "student_programs" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fk_student_programs_structure_id" ON "student_programs" USING btree ("structure_id");--> statement-breakpoint
CREATE INDEX "idx_student_programs_std_no_status" ON "student_programs" USING btree ("std_no","status");--> statement-breakpoint
CREATE INDEX "fk_student_semesters_student_program_id" ON "student_semesters" USING btree ("student_program_id");--> statement-breakpoint
CREATE INDEX "idx_student_semesters_term" ON "student_semesters" USING btree ("term");--> statement-breakpoint
CREATE INDEX "idx_student_semesters_status" ON "student_semesters" USING btree ("status");--> statement-breakpoint
CREATE INDEX "fk_students_user_id" ON "students" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "fk_task_assignments_user_id" ON "task_assignments" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "fk_transcript_prints_std_no" ON "transcript_prints" USING btree ("std_no");--> statement-breakpoint
CREATE INDEX "fk_transcript_prints_printed_by" ON "transcript_prints" USING btree ("printed_by");--> statement-breakpoint
CREATE INDEX "fk_user_schools_user_id" ON "user_schools" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "fk_user_schools_school_id" ON "user_schools" USING btree ("school_id");