ALTER TABLE "subjects" ADD COLUMN "lqf_level" integer;--> statement-breakpoint
UPDATE "subjects" SET "lqf_level" = 4 WHERE "name" IN (
  'English Language',
  'Mathematics',
  'Sesotho',
  'Science (Double Award)',
  'Physical Science',
  'Biology',
  'Chemistry',
  'Physics',
  'Combined Science',
  'Additional Mathematics',
  'Statistics',
  'Literature in English',
  'Geography',
  'History',
  'Religious Studies',
  'Development Studies',
  'Agriculture',
  'Accounting',
  'Business Studies',
  'Economics',
  'Computer Studies',
  'Information and Communication Technology (ICT)',
  'Design and Technology',
  'Food and Nutrition',
  'Fashion and Fabrics',
  'Travel and Tourism',
  'Physical Education',
  'French',
  'Music',
  'Drama',
  'Art',
  'Woodwork',
  'Home Economics',
  'Art and Design',
  'Technical Drawing',
  'Needlework',
  'Bricklaying',
  'Commerce',
  'Entrepreneurship',
  'Metalwork',
  'Building Science',
  'Religious Education',
  'Setswana',
  'Afrikaans',
  'siSwati',
  'IsiZulu',
  'IsiXhosa',
  'Sepedi'
);