-- Seed default mail templates for all trigger types
INSERT INTO mail_templates (id, trigger_type, name, subject, body, is_active, created_at, updated_at)
VALUES
  ('tpl_ss_created', 'student_status_created', 'Student Status Created', 'New Status Request: {{statusType}}', '<p><strong>{{studentName}}</strong> ({{stdNo}}) has submitted a <strong>{{statusType}}</strong> request.</p><p><a href="{{portalUrl}}">View Details</a></p>', true, NOW(), NOW()),
  ('tpl_ss_updated', 'student_status_updated', 'Student Status Updated', 'Status Request Updated: {{statusType}}', '<p><strong>{{studentName}}</strong> ({{stdNo}}) has updated their <strong>{{statusType}}</strong> request.</p><p><a href="{{portalUrl}}">View Details</a></p>', true, NOW(), NOW()),
  ('tpl_ss_approved', 'student_status_approved', 'Student Status Approved', 'Status Request Approved: {{statusType}}', '<p>Your <strong>{{statusType}}</strong> request has been approved by <strong>{{approverName}}</strong>.</p><p><a href="{{portalUrl}}">View Details</a></p>', true, NOW(), NOW()),
  ('tpl_ss_rejected', 'student_status_rejected', 'Student Status Rejected', 'Status Request Rejected: {{statusType}}', '<p>Your <strong>{{statusType}}</strong> request has been rejected by <strong>{{approverName}}</strong>.</p><p>Reason: {{reason}}</p><p><a href="{{portalUrl}}">View Details</a></p>', true, NOW(), NOW()),
  ('tpl_notif_mirror', 'notification_mirror', 'Notification Mirror', '{{title}}', '<p>{{message}}</p><p><a href="{{portalUrl}}">View in Portal</a></p>', true, NOW(), NOW()),
  ('tpl_manual', 'manual', 'Manual Email', '{{title}}', '<p>{{message}}</p>', true, NOW(), NOW()),
  ('tpl_reply', 'reply', 'Reply', '{{title}}', '<p>{{message}}</p>', true, NOW(), NOW()),
  ('tpl_referral', 'referral_created', 'Student Referral Created', 'Student Referral: {{studentName}} ({{stdNo}})', '<p><strong>{{senderName}}</strong> has referred student <strong>{{studentName}}</strong> ({{stdNo}}) for <strong>{{reason}}</strong>.</p><p><a href="{{portalUrl}}">View Referral</a></p>', true, NOW(), NOW()),
  ('tpl_reg_clr_approved', 'registration_clearance_approved', 'Registration Clearance Approved', 'Registration Clearance Approved: {{department}}', '<p>Dear <strong>{{studentName}}</strong> ({{stdNo}}), your registration clearance from <strong>{{department}}</strong> has been approved.</p><p><a href="{{portalUrl}}">View Details</a></p>', true, NOW(), NOW()),
  ('tpl_reg_clr_rejected', 'registration_clearance_rejected', 'Registration Clearance Rejected', 'Registration Clearance Rejected: {{department}}', '<p>Dear <strong>{{studentName}}</strong> ({{stdNo}}), your registration clearance from <strong>{{department}}</strong> has been rejected.</p><p>Reason: {{reason}}</p><p><a href="{{portalUrl}}">View Details</a></p>', true, NOW(), NOW()),
  ('tpl_grad_clr_approved', 'graduation_clearance_approved', 'Graduation Clearance Approved', 'Graduation Clearance Approved: {{department}}', '<p>Dear <strong>{{studentName}}</strong> ({{stdNo}}), your graduation clearance from <strong>{{department}}</strong> has been approved.</p><p><a href="{{portalUrl}}">View Details</a></p>', true, NOW(), NOW()),
  ('tpl_grad_clr_rejected', 'graduation_clearance_rejected', 'Graduation Clearance Rejected', 'Graduation Clearance Rejected: {{department}}', '<p>Dear <strong>{{studentName}}</strong> ({{stdNo}}), your graduation clearance from <strong>{{department}}</strong> has been rejected.</p><p>Reason: {{reason}}</p><p><a href="{{portalUrl}}">View Details</a></p>', true, NOW(), NOW())
ON CONFLICT (trigger_type) DO NOTHING;