interface CountryMeta {
	name: string;
	iso2: string;
	iso3: string;
	phoneCode: string;
	flag: string;
	continent: string;
}

const COUNTRY_DATA: CountryMeta[] = [
	{
		name: 'Afghanistan',
		iso2: 'AF',
		iso3: 'AFG',
		phoneCode: '+93',
		flag: '🇦🇫',
		continent: 'Asia',
	},
	{
		name: 'Albania',
		iso2: 'AL',
		iso3: 'ALB',
		phoneCode: '+355',
		flag: '🇦🇱',
		continent: 'Europe',
	},
	{
		name: 'Algeria',
		iso2: 'DZ',
		iso3: 'DZA',
		phoneCode: '+213',
		flag: '🇩🇿',
		continent: 'Africa',
	},
	{
		name: 'Andorra',
		iso2: 'AD',
		iso3: 'AND',
		phoneCode: '+376',
		flag: '🇦🇩',
		continent: 'Europe',
	},
	{
		name: 'Angola',
		iso2: 'AO',
		iso3: 'AGO',
		phoneCode: '+244',
		flag: '🇦🇴',
		continent: 'Africa',
	},
	{
		name: 'Antigua and Barbuda',
		iso2: 'AG',
		iso3: 'ATG',
		phoneCode: '+1-268',
		flag: '🇦🇬',
		continent: 'North America',
	},
	{
		name: 'Argentina',
		iso2: 'AR',
		iso3: 'ARG',
		phoneCode: '+54',
		flag: '🇦🇷',
		continent: 'South America',
	},
	{
		name: 'Armenia',
		iso2: 'AM',
		iso3: 'ARM',
		phoneCode: '+374',
		flag: '🇦🇲',
		continent: 'Asia',
	},
	{
		name: 'Australia',
		iso2: 'AU',
		iso3: 'AUS',
		phoneCode: '+61',
		flag: '🇦🇺',
		continent: 'Oceania',
	},
	{
		name: 'Austria',
		iso2: 'AT',
		iso3: 'AUT',
		phoneCode: '+43',
		flag: '🇦🇹',
		continent: 'Europe',
	},
	{
		name: 'Azerbaijan',
		iso2: 'AZ',
		iso3: 'AZE',
		phoneCode: '+994',
		flag: '🇦🇿',
		continent: 'Asia',
	},
	{
		name: 'Bahamas',
		iso2: 'BS',
		iso3: 'BHS',
		phoneCode: '+1-242',
		flag: '🇧🇸',
		continent: 'North America',
	},
	{
		name: 'Bahrain',
		iso2: 'BH',
		iso3: 'BHR',
		phoneCode: '+973',
		flag: '🇧🇭',
		continent: 'Asia',
	},
	{
		name: 'Bangladesh',
		iso2: 'BD',
		iso3: 'BGD',
		phoneCode: '+880',
		flag: '🇧🇩',
		continent: 'Asia',
	},
	{
		name: 'Barbados',
		iso2: 'BB',
		iso3: 'BRB',
		phoneCode: '+1-246',
		flag: '🇧🇧',
		continent: 'North America',
	},
	{
		name: 'Belarus',
		iso2: 'BY',
		iso3: 'BLR',
		phoneCode: '+375',
		flag: '🇧🇾',
		continent: 'Europe',
	},
	{
		name: 'Belgium',
		iso2: 'BE',
		iso3: 'BEL',
		phoneCode: '+32',
		flag: '🇧🇪',
		continent: 'Europe',
	},
	{
		name: 'Belize',
		iso2: 'BZ',
		iso3: 'BLZ',
		phoneCode: '+501',
		flag: '🇧🇿',
		continent: 'North America',
	},
	{
		name: 'Benin',
		iso2: 'BJ',
		iso3: 'BEN',
		phoneCode: '+229',
		flag: '🇧🇯',
		continent: 'Africa',
	},
	{
		name: 'Bhutan',
		iso2: 'BT',
		iso3: 'BTN',
		phoneCode: '+975',
		flag: '🇧🇹',
		continent: 'Asia',
	},
	{
		name: 'Bolivia',
		iso2: 'BO',
		iso3: 'BOL',
		phoneCode: '+591',
		flag: '🇧🇴',
		continent: 'South America',
	},
	{
		name: 'Bosnia and Herzegovina',
		iso2: 'BA',
		iso3: 'BIH',
		phoneCode: '+387',
		flag: '🇧🇦',
		continent: 'Europe',
	},
	{
		name: 'Botswana',
		iso2: 'BW',
		iso3: 'BWA',
		phoneCode: '+267',
		flag: '🇧🇼',
		continent: 'Africa',
	},
	{
		name: 'Brazil',
		iso2: 'BR',
		iso3: 'BRA',
		phoneCode: '+55',
		flag: '🇧🇷',
		continent: 'South America',
	},
	{
		name: 'Brunei',
		iso2: 'BN',
		iso3: 'BRN',
		phoneCode: '+673',
		flag: '🇧🇳',
		continent: 'Asia',
	},
	{
		name: 'Bulgaria',
		iso2: 'BG',
		iso3: 'BGR',
		phoneCode: '+359',
		flag: '🇧🇬',
		continent: 'Europe',
	},
	{
		name: 'Burkina Faso',
		iso2: 'BF',
		iso3: 'BFA',
		phoneCode: '+226',
		flag: '🇧🇫',
		continent: 'Africa',
	},
	{
		name: 'Burundi',
		iso2: 'BI',
		iso3: 'BDI',
		phoneCode: '+257',
		flag: '🇧🇮',
		continent: 'Africa',
	},
	{
		name: 'Cabo Verde',
		iso2: 'CV',
		iso3: 'CPV',
		phoneCode: '+238',
		flag: '🇨🇻',
		continent: 'Africa',
	},
	{
		name: 'Cambodia',
		iso2: 'KH',
		iso3: 'KHM',
		phoneCode: '+855',
		flag: '🇰🇭',
		continent: 'Asia',
	},
	{
		name: 'Cameroon',
		iso2: 'CM',
		iso3: 'CMR',
		phoneCode: '+237',
		flag: '🇨🇲',
		continent: 'Africa',
	},
	{
		name: 'Canada',
		iso2: 'CA',
		iso3: 'CAN',
		phoneCode: '+1',
		flag: '🇨🇦',
		continent: 'North America',
	},
	{
		name: 'Central African Republic',
		iso2: 'CF',
		iso3: 'CAF',
		phoneCode: '+236',
		flag: '🇨🇫',
		continent: 'Africa',
	},
	{
		name: 'Chad',
		iso2: 'TD',
		iso3: 'TCD',
		phoneCode: '+235',
		flag: '🇹🇩',
		continent: 'Africa',
	},
	{
		name: 'Chile',
		iso2: 'CL',
		iso3: 'CHL',
		phoneCode: '+56',
		flag: '🇨🇱',
		continent: 'South America',
	},
	{
		name: 'China',
		iso2: 'CN',
		iso3: 'CHN',
		phoneCode: '+86',
		flag: '🇨🇳',
		continent: 'Asia',
	},
	{
		name: 'Colombia',
		iso2: 'CO',
		iso3: 'COL',
		phoneCode: '+57',
		flag: '🇨🇴',
		continent: 'South America',
	},
	{
		name: 'Comoros',
		iso2: 'KM',
		iso3: 'COM',
		phoneCode: '+269',
		flag: '🇰🇲',
		continent: 'Africa',
	},
	{
		name: 'Congo',
		iso2: 'CG',
		iso3: 'COG',
		phoneCode: '+242',
		flag: '🇨🇬',
		continent: 'Africa',
	},
	{
		name: 'Costa Rica',
		iso2: 'CR',
		iso3: 'CRI',
		phoneCode: '+506',
		flag: '🇨🇷',
		continent: 'North America',
	},
	{
		name: 'Croatia',
		iso2: 'HR',
		iso3: 'HRV',
		phoneCode: '+385',
		flag: '🇭🇷',
		continent: 'Europe',
	},
	{
		name: 'Cuba',
		iso2: 'CU',
		iso3: 'CUB',
		phoneCode: '+53',
		flag: '🇨🇺',
		continent: 'North America',
	},
	{
		name: 'Cyprus',
		iso2: 'CY',
		iso3: 'CYP',
		phoneCode: '+357',
		flag: '🇨🇾',
		continent: 'Europe',
	},
	{
		name: 'Czech Republic',
		iso2: 'CZ',
		iso3: 'CZE',
		phoneCode: '+420',
		flag: '🇨🇿',
		continent: 'Europe',
	},
	{
		name: 'DR Congo',
		iso2: 'CD',
		iso3: 'COD',
		phoneCode: '+243',
		flag: '🇨🇩',
		continent: 'Africa',
	},
	{
		name: 'Denmark',
		iso2: 'DK',
		iso3: 'DNK',
		phoneCode: '+45',
		flag: '🇩🇰',
		continent: 'Europe',
	},
	{
		name: 'Djibouti',
		iso2: 'DJ',
		iso3: 'DJI',
		phoneCode: '+253',
		flag: '🇩🇯',
		continent: 'Africa',
	},
	{
		name: 'Dominica',
		iso2: 'DM',
		iso3: 'DMA',
		phoneCode: '+1-767',
		flag: '🇩🇲',
		continent: 'North America',
	},
	{
		name: 'Dominican Republic',
		iso2: 'DO',
		iso3: 'DOM',
		phoneCode: '+1-809',
		flag: '🇩🇴',
		continent: 'North America',
	},
	{
		name: 'Ecuador',
		iso2: 'EC',
		iso3: 'ECU',
		phoneCode: '+593',
		flag: '🇪🇨',
		continent: 'South America',
	},
	{
		name: 'Egypt',
		iso2: 'EG',
		iso3: 'EGY',
		phoneCode: '+20',
		flag: '🇪🇬',
		continent: 'Africa',
	},
	{
		name: 'El Salvador',
		iso2: 'SV',
		iso3: 'SLV',
		phoneCode: '+503',
		flag: '🇸🇻',
		continent: 'North America',
	},
	{
		name: 'Equatorial Guinea',
		iso2: 'GQ',
		iso3: 'GNQ',
		phoneCode: '+240',
		flag: '🇬🇶',
		continent: 'Africa',
	},
	{
		name: 'Eritrea',
		iso2: 'ER',
		iso3: 'ERI',
		phoneCode: '+291',
		flag: '🇪🇷',
		continent: 'Africa',
	},
	{
		name: 'Estonia',
		iso2: 'EE',
		iso3: 'EST',
		phoneCode: '+372',
		flag: '🇪🇪',
		continent: 'Europe',
	},
	{
		name: 'Eswatini',
		iso2: 'SZ',
		iso3: 'SWZ',
		phoneCode: '+268',
		flag: '🇸🇿',
		continent: 'Africa',
	},
	{
		name: 'Ethiopia',
		iso2: 'ET',
		iso3: 'ETH',
		phoneCode: '+251',
		flag: '🇪🇹',
		continent: 'Africa',
	},
	{
		name: 'Fiji',
		iso2: 'FJ',
		iso3: 'FJI',
		phoneCode: '+679',
		flag: '🇫🇯',
		continent: 'Oceania',
	},
	{
		name: 'Finland',
		iso2: 'FI',
		iso3: 'FIN',
		phoneCode: '+358',
		flag: '🇫🇮',
		continent: 'Europe',
	},
	{
		name: 'France',
		iso2: 'FR',
		iso3: 'FRA',
		phoneCode: '+33',
		flag: '🇫🇷',
		continent: 'Europe',
	},
	{
		name: 'Gabon',
		iso2: 'GA',
		iso3: 'GAB',
		phoneCode: '+241',
		flag: '🇬🇦',
		continent: 'Africa',
	},
	{
		name: 'Gambia',
		iso2: 'GM',
		iso3: 'GMB',
		phoneCode: '+220',
		flag: '🇬🇲',
		continent: 'Africa',
	},
	{
		name: 'Georgia',
		iso2: 'GE',
		iso3: 'GEO',
		phoneCode: '+995',
		flag: '🇬🇪',
		continent: 'Asia',
	},
	{
		name: 'Germany',
		iso2: 'DE',
		iso3: 'DEU',
		phoneCode: '+49',
		flag: '🇩🇪',
		continent: 'Europe',
	},
	{
		name: 'Ghana',
		iso2: 'GH',
		iso3: 'GHA',
		phoneCode: '+233',
		flag: '🇬🇭',
		continent: 'Africa',
	},
	{
		name: 'Greece',
		iso2: 'GR',
		iso3: 'GRC',
		phoneCode: '+30',
		flag: '🇬🇷',
		continent: 'Europe',
	},
	{
		name: 'Grenada',
		iso2: 'GD',
		iso3: 'GRD',
		phoneCode: '+1-473',
		flag: '🇬🇩',
		continent: 'North America',
	},
	{
		name: 'Guatemala',
		iso2: 'GT',
		iso3: 'GTM',
		phoneCode: '+502',
		flag: '🇬🇹',
		continent: 'North America',
	},
	{
		name: 'Guinea',
		iso2: 'GN',
		iso3: 'GIN',
		phoneCode: '+224',
		flag: '🇬🇳',
		continent: 'Africa',
	},
	{
		name: 'Guinea-Bissau',
		iso2: 'GW',
		iso3: 'GNB',
		phoneCode: '+245',
		flag: '🇬🇼',
		continent: 'Africa',
	},
	{
		name: 'Guyana',
		iso2: 'GY',
		iso3: 'GUY',
		phoneCode: '+592',
		flag: '🇬🇾',
		continent: 'South America',
	},
	{
		name: 'Haiti',
		iso2: 'HT',
		iso3: 'HTI',
		phoneCode: '+509',
		flag: '🇭🇹',
		continent: 'North America',
	},
	{
		name: 'Honduras',
		iso2: 'HN',
		iso3: 'HND',
		phoneCode: '+504',
		flag: '🇭🇳',
		continent: 'North America',
	},
	{
		name: 'Hungary',
		iso2: 'HU',
		iso3: 'HUN',
		phoneCode: '+36',
		flag: '🇭🇺',
		continent: 'Europe',
	},
	{
		name: 'Iceland',
		iso2: 'IS',
		iso3: 'ISL',
		phoneCode: '+354',
		flag: '🇮🇸',
		continent: 'Europe',
	},
	{
		name: 'India',
		iso2: 'IN',
		iso3: 'IND',
		phoneCode: '+91',
		flag: '🇮🇳',
		continent: 'Asia',
	},
	{
		name: 'Indonesia',
		iso2: 'ID',
		iso3: 'IDN',
		phoneCode: '+62',
		flag: '🇮🇩',
		continent: 'Asia',
	},
	{
		name: 'Iran',
		iso2: 'IR',
		iso3: 'IRN',
		phoneCode: '+98',
		flag: '🇮🇷',
		continent: 'Asia',
	},
	{
		name: 'Iraq',
		iso2: 'IQ',
		iso3: 'IRQ',
		phoneCode: '+964',
		flag: '🇮🇶',
		continent: 'Asia',
	},
	{
		name: 'Ireland',
		iso2: 'IE',
		iso3: 'IRL',
		phoneCode: '+353',
		flag: '🇮🇪',
		continent: 'Europe',
	},
	{
		name: 'Israel',
		iso2: 'IL',
		iso3: 'ISR',
		phoneCode: '+972',
		flag: '🇮🇱',
		continent: 'Asia',
	},
	{
		name: 'Italy',
		iso2: 'IT',
		iso3: 'ITA',
		phoneCode: '+39',
		flag: '🇮🇹',
		continent: 'Europe',
	},
	{
		name: 'Ivory Coast',
		iso2: 'CI',
		iso3: 'CIV',
		phoneCode: '+225',
		flag: '🇨🇮',
		continent: 'Africa',
	},
	{
		name: 'Jamaica',
		iso2: 'JM',
		iso3: 'JAM',
		phoneCode: '+1-876',
		flag: '🇯🇲',
		continent: 'North America',
	},
	{
		name: 'Japan',
		iso2: 'JP',
		iso3: 'JPN',
		phoneCode: '+81',
		flag: '🇯🇵',
		continent: 'Asia',
	},
	{
		name: 'Jordan',
		iso2: 'JO',
		iso3: 'JOR',
		phoneCode: '+962',
		flag: '🇯🇴',
		continent: 'Asia',
	},
	{
		name: 'Kazakhstan',
		iso2: 'KZ',
		iso3: 'KAZ',
		phoneCode: '+7',
		flag: '🇰🇿',
		continent: 'Asia',
	},
	{
		name: 'Kenya',
		iso2: 'KE',
		iso3: 'KEN',
		phoneCode: '+254',
		flag: '🇰🇪',
		continent: 'Africa',
	},
	{
		name: 'Kiribati',
		iso2: 'KI',
		iso3: 'KIR',
		phoneCode: '+686',
		flag: '🇰🇮',
		continent: 'Oceania',
	},
	{
		name: 'Kuwait',
		iso2: 'KW',
		iso3: 'KWT',
		phoneCode: '+965',
		flag: '🇰🇼',
		continent: 'Asia',
	},
	{
		name: 'Kyrgyzstan',
		iso2: 'KG',
		iso3: 'KGZ',
		phoneCode: '+996',
		flag: '🇰🇬',
		continent: 'Asia',
	},
	{
		name: 'Laos',
		iso2: 'LA',
		iso3: 'LAO',
		phoneCode: '+856',
		flag: '🇱🇦',
		continent: 'Asia',
	},
	{
		name: 'Latvia',
		iso2: 'LV',
		iso3: 'LVA',
		phoneCode: '+371',
		flag: '🇱🇻',
		continent: 'Europe',
	},
	{
		name: 'Lebanon',
		iso2: 'LB',
		iso3: 'LBN',
		phoneCode: '+961',
		flag: '🇱🇧',
		continent: 'Asia',
	},
	{
		name: 'Lesotho',
		iso2: 'LS',
		iso3: 'LSO',
		phoneCode: '+266',
		flag: '🇱🇸',
		continent: 'Africa',
	},
	{
		name: 'Liberia',
		iso2: 'LR',
		iso3: 'LBR',
		phoneCode: '+231',
		flag: '🇱🇷',
		continent: 'Africa',
	},
	{
		name: 'Libya',
		iso2: 'LY',
		iso3: 'LBY',
		phoneCode: '+218',
		flag: '🇱🇾',
		continent: 'Africa',
	},
	{
		name: 'Liechtenstein',
		iso2: 'LI',
		iso3: 'LIE',
		phoneCode: '+423',
		flag: '🇱🇮',
		continent: 'Europe',
	},
	{
		name: 'Lithuania',
		iso2: 'LT',
		iso3: 'LTU',
		phoneCode: '+370',
		flag: '🇱🇹',
		continent: 'Europe',
	},
	{
		name: 'Luxembourg',
		iso2: 'LU',
		iso3: 'LUX',
		phoneCode: '+352',
		flag: '🇱🇺',
		continent: 'Europe',
	},
	{
		name: 'Madagascar',
		iso2: 'MG',
		iso3: 'MDG',
		phoneCode: '+261',
		flag: '🇲🇬',
		continent: 'Africa',
	},
	{
		name: 'Malawi',
		iso2: 'MW',
		iso3: 'MWI',
		phoneCode: '+265',
		flag: '🇲🇼',
		continent: 'Africa',
	},
	{
		name: 'Malaysia',
		iso2: 'MY',
		iso3: 'MYS',
		phoneCode: '+60',
		flag: '🇲🇾',
		continent: 'Asia',
	},
	{
		name: 'Maldives',
		iso2: 'MV',
		iso3: 'MDV',
		phoneCode: '+960',
		flag: '🇲🇻',
		continent: 'Asia',
	},
	{
		name: 'Mali',
		iso2: 'ML',
		iso3: 'MLI',
		phoneCode: '+223',
		flag: '🇲🇱',
		continent: 'Africa',
	},
	{
		name: 'Malta',
		iso2: 'MT',
		iso3: 'MLT',
		phoneCode: '+356',
		flag: '🇲🇹',
		continent: 'Europe',
	},
	{
		name: 'Marshall Islands',
		iso2: 'MH',
		iso3: 'MHL',
		phoneCode: '+692',
		flag: '🇲🇭',
		continent: 'Oceania',
	},
	{
		name: 'Mauritania',
		iso2: 'MR',
		iso3: 'MRT',
		phoneCode: '+222',
		flag: '🇲🇷',
		continent: 'Africa',
	},
	{
		name: 'Mauritius',
		iso2: 'MU',
		iso3: 'MUS',
		phoneCode: '+230',
		flag: '🇲🇺',
		continent: 'Africa',
	},
	{
		name: 'Mexico',
		iso2: 'MX',
		iso3: 'MEX',
		phoneCode: '+52',
		flag: '🇲🇽',
		continent: 'North America',
	},
	{
		name: 'Micronesia',
		iso2: 'FM',
		iso3: 'FSM',
		phoneCode: '+691',
		flag: '🇫🇲',
		continent: 'Oceania',
	},
	{
		name: 'Moldova',
		iso2: 'MD',
		iso3: 'MDA',
		phoneCode: '+373',
		flag: '🇲🇩',
		continent: 'Europe',
	},
	{
		name: 'Monaco',
		iso2: 'MC',
		iso3: 'MCO',
		phoneCode: '+377',
		flag: '🇲🇨',
		continent: 'Europe',
	},
	{
		name: 'Mongolia',
		iso2: 'MN',
		iso3: 'MNG',
		phoneCode: '+976',
		flag: '🇲🇳',
		continent: 'Asia',
	},
	{
		name: 'Montenegro',
		iso2: 'ME',
		iso3: 'MNE',
		phoneCode: '+382',
		flag: '🇲🇪',
		continent: 'Europe',
	},
	{
		name: 'Morocco',
		iso2: 'MA',
		iso3: 'MAR',
		phoneCode: '+212',
		flag: '🇲🇦',
		continent: 'Africa',
	},
	{
		name: 'Mozambique',
		iso2: 'MZ',
		iso3: 'MOZ',
		phoneCode: '+258',
		flag: '🇲🇿',
		continent: 'Africa',
	},
	{
		name: 'Myanmar',
		iso2: 'MM',
		iso3: 'MMR',
		phoneCode: '+95',
		flag: '🇲🇲',
		continent: 'Asia',
	},
	{
		name: 'Namibia',
		iso2: 'NA',
		iso3: 'NAM',
		phoneCode: '+264',
		flag: '🇳🇦',
		continent: 'Africa',
	},
	{
		name: 'Nauru',
		iso2: 'NR',
		iso3: 'NRU',
		phoneCode: '+674',
		flag: '🇳🇷',
		continent: 'Oceania',
	},
	{
		name: 'Nepal',
		iso2: 'NP',
		iso3: 'NPL',
		phoneCode: '+977',
		flag: '🇳🇵',
		continent: 'Asia',
	},
	{
		name: 'Netherlands',
		iso2: 'NL',
		iso3: 'NLD',
		phoneCode: '+31',
		flag: '🇳🇱',
		continent: 'Europe',
	},
	{
		name: 'New Zealand',
		iso2: 'NZ',
		iso3: 'NZL',
		phoneCode: '+64',
		flag: '🇳🇿',
		continent: 'Oceania',
	},
	{
		name: 'Nicaragua',
		iso2: 'NI',
		iso3: 'NIC',
		phoneCode: '+505',
		flag: '🇳🇮',
		continent: 'North America',
	},
	{
		name: 'Niger',
		iso2: 'NE',
		iso3: 'NER',
		phoneCode: '+227',
		flag: '🇳🇪',
		continent: 'Africa',
	},
	{
		name: 'Nigeria',
		iso2: 'NG',
		iso3: 'NGA',
		phoneCode: '+234',
		flag: '🇳🇬',
		continent: 'Africa',
	},
	{
		name: 'North Korea',
		iso2: 'KP',
		iso3: 'PRK',
		phoneCode: '+850',
		flag: '🇰🇵',
		continent: 'Asia',
	},
	{
		name: 'North Macedonia',
		iso2: 'MK',
		iso3: 'MKD',
		phoneCode: '+389',
		flag: '🇲🇰',
		continent: 'Europe',
	},
	{
		name: 'Norway',
		iso2: 'NO',
		iso3: 'NOR',
		phoneCode: '+47',
		flag: '🇳🇴',
		continent: 'Europe',
	},
	{
		name: 'Oman',
		iso2: 'OM',
		iso3: 'OMN',
		phoneCode: '+968',
		flag: '🇴🇲',
		continent: 'Asia',
	},
	{
		name: 'Pakistan',
		iso2: 'PK',
		iso3: 'PAK',
		phoneCode: '+92',
		flag: '🇵🇰',
		continent: 'Asia',
	},
	{
		name: 'Palau',
		iso2: 'PW',
		iso3: 'PLW',
		phoneCode: '+680',
		flag: '🇵🇼',
		continent: 'Oceania',
	},
	{
		name: 'Palestine',
		iso2: 'PS',
		iso3: 'PSE',
		phoneCode: '+970',
		flag: '🇵🇸',
		continent: 'Asia',
	},
	{
		name: 'Panama',
		iso2: 'PA',
		iso3: 'PAN',
		phoneCode: '+507',
		flag: '🇵🇦',
		continent: 'North America',
	},
	{
		name: 'Papua New Guinea',
		iso2: 'PG',
		iso3: 'PNG',
		phoneCode: '+675',
		flag: '🇵🇬',
		continent: 'Oceania',
	},
	{
		name: 'Paraguay',
		iso2: 'PY',
		iso3: 'PRY',
		phoneCode: '+595',
		flag: '🇵🇾',
		continent: 'South America',
	},
	{
		name: 'Peru',
		iso2: 'PE',
		iso3: 'PER',
		phoneCode: '+51',
		flag: '🇵🇪',
		continent: 'South America',
	},
	{
		name: 'Philippines',
		iso2: 'PH',
		iso3: 'PHL',
		phoneCode: '+63',
		flag: '🇵🇭',
		continent: 'Asia',
	},
	{
		name: 'Poland',
		iso2: 'PL',
		iso3: 'POL',
		phoneCode: '+48',
		flag: '🇵🇱',
		continent: 'Europe',
	},
	{
		name: 'Portugal',
		iso2: 'PT',
		iso3: 'PRT',
		phoneCode: '+351',
		flag: '🇵🇹',
		continent: 'Europe',
	},
	{
		name: 'Qatar',
		iso2: 'QA',
		iso3: 'QAT',
		phoneCode: '+974',
		flag: '🇶🇦',
		continent: 'Asia',
	},
	{
		name: 'Romania',
		iso2: 'RO',
		iso3: 'ROU',
		phoneCode: '+40',
		flag: '🇷🇴',
		continent: 'Europe',
	},
	{
		name: 'Russia',
		iso2: 'RU',
		iso3: 'RUS',
		phoneCode: '+7',
		flag: '🇷🇺',
		continent: 'Europe',
	},
	{
		name: 'Rwanda',
		iso2: 'RW',
		iso3: 'RWA',
		phoneCode: '+250',
		flag: '🇷🇼',
		continent: 'Africa',
	},
	{
		name: 'Saint Kitts and Nevis',
		iso2: 'KN',
		iso3: 'KNA',
		phoneCode: '+1-869',
		flag: '🇰🇳',
		continent: 'North America',
	},
	{
		name: 'Saint Lucia',
		iso2: 'LC',
		iso3: 'LCA',
		phoneCode: '+1-758',
		flag: '🇱🇨',
		continent: 'North America',
	},
	{
		name: 'Saint Vincent and the Grenadines',
		iso2: 'VC',
		iso3: 'VCT',
		phoneCode: '+1-784',
		flag: '🇻🇨',
		continent: 'North America',
	},
	{
		name: 'Samoa',
		iso2: 'WS',
		iso3: 'WSM',
		phoneCode: '+685',
		flag: '🇼🇸',
		continent: 'Oceania',
	},
	{
		name: 'San Marino',
		iso2: 'SM',
		iso3: 'SMR',
		phoneCode: '+378',
		flag: '🇸🇲',
		continent: 'Europe',
	},
	{
		name: 'Sao Tome and Principe',
		iso2: 'ST',
		iso3: 'STP',
		phoneCode: '+239',
		flag: '🇸🇹',
		continent: 'Africa',
	},
	{
		name: 'Saudi Arabia',
		iso2: 'SA',
		iso3: 'SAU',
		phoneCode: '+966',
		flag: '🇸🇦',
		continent: 'Asia',
	},
	{
		name: 'Senegal',
		iso2: 'SN',
		iso3: 'SEN',
		phoneCode: '+221',
		flag: '🇸🇳',
		continent: 'Africa',
	},
	{
		name: 'Serbia',
		iso2: 'RS',
		iso3: 'SRB',
		phoneCode: '+381',
		flag: '🇷🇸',
		continent: 'Europe',
	},
	{
		name: 'Seychelles',
		iso2: 'SC',
		iso3: 'SYC',
		phoneCode: '+248',
		flag: '🇸🇨',
		continent: 'Africa',
	},
	{
		name: 'Sierra Leone',
		iso2: 'SL',
		iso3: 'SLE',
		phoneCode: '+232',
		flag: '🇸🇱',
		continent: 'Africa',
	},
	{
		name: 'Singapore',
		iso2: 'SG',
		iso3: 'SGP',
		phoneCode: '+65',
		flag: '🇸🇬',
		continent: 'Asia',
	},
	{
		name: 'Slovakia',
		iso2: 'SK',
		iso3: 'SVK',
		phoneCode: '+421',
		flag: '🇸🇰',
		continent: 'Europe',
	},
	{
		name: 'Slovenia',
		iso2: 'SI',
		iso3: 'SVN',
		phoneCode: '+386',
		flag: '🇸🇮',
		continent: 'Europe',
	},
	{
		name: 'Solomon Islands',
		iso2: 'SB',
		iso3: 'SLB',
		phoneCode: '+677',
		flag: '🇸🇧',
		continent: 'Oceania',
	},
	{
		name: 'Somalia',
		iso2: 'SO',
		iso3: 'SOM',
		phoneCode: '+252',
		flag: '🇸🇴',
		continent: 'Africa',
	},
	{
		name: 'South Africa',
		iso2: 'ZA',
		iso3: 'ZAF',
		phoneCode: '+27',
		flag: '🇿🇦',
		continent: 'Africa',
	},
	{
		name: 'South Korea',
		iso2: 'KR',
		iso3: 'KOR',
		phoneCode: '+82',
		flag: '🇰🇷',
		continent: 'Asia',
	},
	{
		name: 'South Sudan',
		iso2: 'SS',
		iso3: 'SSD',
		phoneCode: '+211',
		flag: '🇸🇸',
		continent: 'Africa',
	},
	{
		name: 'Spain',
		iso2: 'ES',
		iso3: 'ESP',
		phoneCode: '+34',
		flag: '🇪🇸',
		continent: 'Europe',
	},
	{
		name: 'Sri Lanka',
		iso2: 'LK',
		iso3: 'LKA',
		phoneCode: '+94',
		flag: '🇱🇰',
		continent: 'Asia',
	},
	{
		name: 'Sudan',
		iso2: 'SD',
		iso3: 'SDN',
		phoneCode: '+249',
		flag: '🇸🇩',
		continent: 'Africa',
	},
	{
		name: 'Suriname',
		iso2: 'SR',
		iso3: 'SUR',
		phoneCode: '+597',
		flag: '🇸🇷',
		continent: 'South America',
	},
	{
		name: 'Sweden',
		iso2: 'SE',
		iso3: 'SWE',
		phoneCode: '+46',
		flag: '🇸🇪',
		continent: 'Europe',
	},
	{
		name: 'Switzerland',
		iso2: 'CH',
		iso3: 'CHE',
		phoneCode: '+41',
		flag: '🇨🇭',
		continent: 'Europe',
	},
	{
		name: 'Syria',
		iso2: 'SY',
		iso3: 'SYR',
		phoneCode: '+963',
		flag: '🇸🇾',
		continent: 'Asia',
	},
	{
		name: 'Taiwan',
		iso2: 'TW',
		iso3: 'TWN',
		phoneCode: '+886',
		flag: '🇹🇼',
		continent: 'Asia',
	},
	{
		name: 'Tajikistan',
		iso2: 'TJ',
		iso3: 'TJK',
		phoneCode: '+992',
		flag: '🇹🇯',
		continent: 'Asia',
	},
	{
		name: 'Tanzania',
		iso2: 'TZ',
		iso3: 'TZA',
		phoneCode: '+255',
		flag: '🇹🇿',
		continent: 'Africa',
	},
	{
		name: 'Thailand',
		iso2: 'TH',
		iso3: 'THA',
		phoneCode: '+66',
		flag: '🇹🇭',
		continent: 'Asia',
	},
	{
		name: 'Timor-Leste',
		iso2: 'TL',
		iso3: 'TLS',
		phoneCode: '+670',
		flag: '🇹🇱',
		continent: 'Asia',
	},
	{
		name: 'Togo',
		iso2: 'TG',
		iso3: 'TGO',
		phoneCode: '+228',
		flag: '🇹🇬',
		continent: 'Africa',
	},
	{
		name: 'Tonga',
		iso2: 'TO',
		iso3: 'TON',
		phoneCode: '+676',
		flag: '🇹🇴',
		continent: 'Oceania',
	},
	{
		name: 'Trinidad and Tobago',
		iso2: 'TT',
		iso3: 'TTO',
		phoneCode: '+1-868',
		flag: '🇹🇹',
		continent: 'North America',
	},
	{
		name: 'Tunisia',
		iso2: 'TN',
		iso3: 'TUN',
		phoneCode: '+216',
		flag: '🇹🇳',
		continent: 'Africa',
	},
	{
		name: 'Turkey',
		iso2: 'TR',
		iso3: 'TUR',
		phoneCode: '+90',
		flag: '🇹🇷',
		continent: 'Asia',
	},
	{
		name: 'Turkmenistan',
		iso2: 'TM',
		iso3: 'TKM',
		phoneCode: '+993',
		flag: '🇹🇲',
		continent: 'Asia',
	},
	{
		name: 'Tuvalu',
		iso2: 'TV',
		iso3: 'TUV',
		phoneCode: '+688',
		flag: '🇹🇻',
		continent: 'Oceania',
	},
	{
		name: 'Uganda',
		iso2: 'UG',
		iso3: 'UGA',
		phoneCode: '+256',
		flag: '🇺🇬',
		continent: 'Africa',
	},
	{
		name: 'Ukraine',
		iso2: 'UA',
		iso3: 'UKR',
		phoneCode: '+380',
		flag: '🇺🇦',
		continent: 'Europe',
	},
	{
		name: 'United Arab Emirates',
		iso2: 'AE',
		iso3: 'ARE',
		phoneCode: '+971',
		flag: '🇦🇪',
		continent: 'Asia',
	},
	{
		name: 'United Kingdom',
		iso2: 'GB',
		iso3: 'GBR',
		phoneCode: '+44',
		flag: '🇬🇧',
		continent: 'Europe',
	},
	{
		name: 'United States',
		iso2: 'US',
		iso3: 'USA',
		phoneCode: '+1',
		flag: '🇺🇸',
		continent: 'North America',
	},
	{
		name: 'Uruguay',
		iso2: 'UY',
		iso3: 'URY',
		phoneCode: '+598',
		flag: '🇺🇾',
		continent: 'South America',
	},
	{
		name: 'Uzbekistan',
		iso2: 'UZ',
		iso3: 'UZB',
		phoneCode: '+998',
		flag: '🇺🇿',
		continent: 'Asia',
	},
	{
		name: 'Vanuatu',
		iso2: 'VU',
		iso3: 'VUT',
		phoneCode: '+678',
		flag: '🇻🇺',
		continent: 'Oceania',
	},
	{
		name: 'Vatican City',
		iso2: 'VA',
		iso3: 'VAT',
		phoneCode: '+379',
		flag: '🇻🇦',
		continent: 'Europe',
	},
	{
		name: 'Venezuela',
		iso2: 'VE',
		iso3: 'VEN',
		phoneCode: '+58',
		flag: '🇻🇪',
		continent: 'South America',
	},
	{
		name: 'Vietnam',
		iso2: 'VN',
		iso3: 'VNM',
		phoneCode: '+84',
		flag: '🇻🇳',
		continent: 'Asia',
	},
	{
		name: 'Yemen',
		iso2: 'YE',
		iso3: 'YEM',
		phoneCode: '+967',
		flag: '🇾🇪',
		continent: 'Asia',
	},
	{
		name: 'Zambia',
		iso2: 'ZM',
		iso3: 'ZMB',
		phoneCode: '+260',
		flag: '🇿🇲',
		continent: 'Africa',
	},
	{
		name: 'Zimbabwe',
		iso2: 'ZW',
		iso3: 'ZWE',
		phoneCode: '+263',
		flag: '🇿🇼',
		continent: 'Africa',
	},
];

const NATIONALITY_MAP: Record<string, string> = {
	mosotho: 'Lesotho',
	basotho: 'Lesotho',
	sotho: 'Lesotho',
	lesotho: 'Lesotho',
	swazi: 'Eswatini',
	eswatini: 'Eswatini',
	swaziland: 'Eswatini',
	liswati: 'Eswatini',
	'south african': 'South Africa',
	rsa: 'South Africa',
	'south africa': 'South Africa',
	motswana: 'Botswana',
	batswana: 'Botswana',
	tswana: 'Botswana',
	botswana: 'Botswana',
	zimbabwean: 'Zimbabwe',
	zimbabwe: 'Zimbabwe',
	mozambican: 'Mozambique',
	mozambique: 'Mozambique',
	namibian: 'Namibia',
	namibia: 'Namibia',
	zambian: 'Zambia',
	zambia: 'Zambia',
	malawian: 'Malawi',
	malawi: 'Malawi',
	malaysian: 'Malaysia',
	malaysia: 'Malaysia',
	nigerian: 'Nigeria',
	nigeria: 'Nigeria',
	ghanaian: 'Ghana',
	ghana: 'Ghana',
	kenyan: 'Kenya',
	kenya: 'Kenya',
	tanzanian: 'Tanzania',
	tanzania: 'Tanzania',
	ugandan: 'Uganda',
	uganda: 'Uganda',
	indian: 'India',
	india: 'India',
	chinese: 'China',
	china: 'China',
	pakistani: 'Pakistan',
	pakistan: 'Pakistan',
	afghan: 'Afghanistan',
	afghanistan: 'Afghanistan',
	japanese: 'Japan',
	japan: 'Japan',
	'south korean': 'South Korea',
	'south korea': 'South Korea',
	lebanese: 'Lebanon',
	lebanon: 'Lebanon',
	omani: 'Oman',
	oman: 'Oman',
	norwegian: 'Norway',
	norway: 'Norway',
	romanian: 'Romania',
	romania: 'Romania',
	'saint lucian': 'Saint Lucia',
	'saint lucia': 'Saint Lucia',
	palauan: 'Palau',
	palau: 'Palau',
	peruvian: 'Peru',
	peru: 'Peru',
	norfuk: 'Australia',
	tajik: 'Tajikistan',
	tajikistan: 'Tajikistan',
	maldivian: 'Maldives',
	maldives: 'Maldives',
};

export type { CountryMeta };

export function getCountryData(): CountryMeta[] {
	return COUNTRY_DATA;
}

export function getCountries(): string[] {
	return COUNTRY_DATA.map((c) => c.name);
}

export function getCountryByName(name: string): CountryMeta | undefined {
	return COUNTRY_DATA.find((c) => c.name.toLowerCase() === name.toLowerCase());
}

export function getCountryByIso2(iso2: string): CountryMeta | undefined {
	return COUNTRY_DATA.find((c) => c.iso2.toLowerCase() === iso2.toLowerCase());
}

export function getCountrySelectData(): { value: string; label: string }[] {
	return COUNTRY_DATA.map((c) => ({
		value: c.name,
		label: `${c.flag} ${c.name}`,
	}));
}

export function getPhoneCodeSelectData(): { value: string; label: string }[] {
	return COUNTRY_DATA.map((c) => ({
		value: c.phoneCode,
		label: `${c.flag} ${c.name} (${c.phoneCode})`,
	}));
}

export function normalizeNationality(
	value: string | null | undefined
): string | null {
	if (!value) return null;
	const trimmed = value.trim();
	if (!trimmed) return null;
	const key = trimmed.toLowerCase();
	return NATIONALITY_MAP[key] ?? null;
}
