const COUNTRIES = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Antigua and Barbuda',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cabo Verde',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo',
	'Costa Rica',
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czech Republic',
	'DR Congo',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Eswatini',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Grenada',
	'Guatemala',
	'Guinea',
	'Guinea-Bissau',
	'Guyana',
	'Haiti',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Ivory Coast',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Micronesia',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Korea',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Palestine',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saint Kitts and Nevis',
	'Saint Lucia',
	'Saint Vincent and the Grenadines',
	'Samoa',
	'San Marino',
	'Sao Tome and Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Korea',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Tonga',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Vatican City',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe',
] as const;

type Country = (typeof COUNTRIES)[number];

const NATIONALITY_MAP: Record<string, Country> = {
	mosotho: 'Lesotho',
	basotho: 'Lesotho',
	sotho: 'Lesotho',
	lesotho: 'Lesotho',
	swazi: 'Eswatini',
	eswatini: 'Eswatini',
	swaziland: 'Eswatini',
	liswati: 'Eswatini',
	'south african': 'South Africa',
	rsa: 'South Africa',
	'south africa': 'South Africa',
	motswana: 'Botswana',
	batswana: 'Botswana',
	tswana: 'Botswana',
	botswana: 'Botswana',
	zimbabwean: 'Zimbabwe',
	zimbabwe: 'Zimbabwe',
	mozambican: 'Mozambique',
	mozambique: 'Mozambique',
	namibian: 'Namibia',
	namibia: 'Namibia',
	zambian: 'Zambia',
	zambia: 'Zambia',
	malawian: 'Malawi',
	malawi: 'Malawi',
	malaysian: 'Malaysia',
	malaysia: 'Malaysia',
	nigerian: 'Nigeria',
	nigeria: 'Nigeria',
	ghanaian: 'Ghana',
	ghana: 'Ghana',
	kenyan: 'Kenya',
	kenya: 'Kenya',
	tanzanian: 'Tanzania',
	tanzania: 'Tanzania',
	ugandan: 'Uganda',
	uganda: 'Uganda',
	indian: 'India',
	india: 'India',
	chinese: 'China',
	china: 'China',
	pakistani: 'Pakistan',
	pakistan: 'Pakistan',
	afghan: 'Afghanistan',
	afghanistan: 'Afghanistan',
	japanese: 'Japan',
	japan: 'Japan',
	'south korean': 'South Korea',
	'south korea': 'South Korea',
	lebanese: 'Lebanon',
	lebanon: 'Lebanon',
	omani: 'Oman',
	oman: 'Oman',
	norwegian: 'Norway',
	norway: 'Norway',
	romanian: 'Romania',
	romania: 'Romania',
	'saint lucian': 'Saint Lucia',
	'saint lucia': 'Saint Lucia',
	palauan: 'Palau',
	palau: 'Palau',
	peruvian: 'Peru',
	peru: 'Peru',
	norfuk: 'Australia',
	tajik: 'Tajikistan',
	tajikistan: 'Tajikistan',
	maldivian: 'Maldives',
	maldives: 'Maldives',
};

export function normalizeNationality(
	value: string | null | undefined
): string | null {
	if (!value) return null;
	const trimmed = value.trim();
	if (!trimmed) return null;
	const key = trimmed.toLowerCase();
	return NATIONALITY_MAP[key] ?? null;
}

export function getCountries(): string[] {
	return [...COUNTRIES];
}
