export type PostType = 'announcement' | 'discussion';

export type MoodleForum = {
	id: number;
	course: number;
	type: string;
	name: string;
	intro: string;
	introformat: number;
	assessed: number;
	assesstimestart: number;
	assesstimefinish: number;
	scale: number;
	maxbytes: number;
	maxattachments: number;
	forcesubscribe: number;
	trackingtype: number;
	rsstype: number;
	rssarticles: number;
	timemodified: number;
	warnafter: number;
	blockafter: number;
	blockperiod: number;
	completiondiscussions: number;
	completionreplies: number;
	completionposts: number;
	cmid: number;
	numdiscussions?: number;
	cancreatediscussions?: boolean;
	istracked?: boolean;
};

export type MoodleDiscussion = {
	id: number;
	name: string;
	groupid: number;
	timemodified: number;
	usermodified: number;
	timestart: number;
	timeend: number;
	discussion: number;
	parent: number;
	userid: number;
	created: number;
	modified: number;
	mailed: number;
	subject: string;
	message: string;
	messageformat: number;
	messagetrust: number;
	attachment: string;
	totalscore: number;
	mailnow: number;
	userfullname: string;
	usermodifiedfullname?: string;
	userpictureurl: string;
	usermodifiedpictureurl?: string;
	numreplies: number;
	numunread: number;
	pinned: boolean;
	locked: boolean;
	starred?: boolean;
	canreply?: boolean;
	canlock?: boolean;
	canfavourite?: boolean;
};

export type CreatePostParams = {
	courseId: number;
	postType: PostType;
	subject: string;
	message: string;
};
