export type MoodleCourse = {
	id: number;
	shortname: string;
	fullname: string;
	displayname?: string;
	enrolledusercount?: number;
	idnumber: string;
	visible: number;
	summary?: string;
	summaryformat?: number;
	format?: string;
	courseimage?: string;
	showgrades?: number | boolean;
	lang: string;
	enablecompletion?: number | boolean;
	completionhascriteria?: number | boolean;
	completionusertracked?: number | boolean;
	category?: number;
	progress?: number | null;
	completed?: number | boolean | null;
	startdate?: number;
	enddate?: number;
	marker?: number;
	lastaccess: number | null;
	isfavourite?: number | boolean;
	hidden?: number | boolean;
	overviewfiles: Array<{
		filename: string;
		filepath: string;
		filesize: number;
		fileurl: string;
		timemodified: number;
		mimetype: string;
		isexternalfile?: number;
		repositorytype?: string;
		icon?: string;
	}>;
	showactivitydates?: number | boolean;
	showcompletionconditions?: number | boolean;
	timemodified?: number;
};
