export { auditLogs } from '@/core/database/schema/auditLogs';
export { auditLogsRelations } from '@/core/database/schema/auditLogsRelations';
export * from '../student-modules/_schema/relations';
export * from '../student-modules/_schema/studentModuleAuditLogs';
export * from '../student-programs/_schema/relations';
export * from '../student-programs/_schema/studentProgramAuditLogs';
export * from '../student-semesters/_schema/relations';
export * from '../student-semesters/_schema/studentSemesterAuditLogs';
export * from '../students/_schema/relations';
export * from '../students/_schema/studentAuditLogs';
