export interface AssessmentType {
  id: string
  label: string
}

export interface AssessmentNumberOption {
  value: string
  label: string
}

export const COURSE_WORK_OPTIONS: AssessmentNumberOption[] = [
  { value: 'CW1', label: 'Course Work 1' },
  { value: 'CW2', label: 'Course Work 2' },
  { value: 'CW3', label: 'Course Work 3' },
  { value: 'CW4', label: 'Course Work 4' },
  { value: 'CW5', label: 'Course Work 5' },
  { value: 'CW6', label: 'Course Work 6' },
  { value: 'CW7', label: 'Course Work 7' },
  { value: 'CW8', label: 'Course Work 8' },
  { value: 'CW9', label: 'Course Work 9' },
  { value: 'CW10', label: 'Course Work 10' },
  { value: 'CW11', label: 'Course Work 11' },
  { value: 'CW12', label: 'Course Work 12' },
  { value: 'CW13', label: 'Course Work 13' },
  { value: 'CW14', label: 'Course Work 14' },
  { value: 'CW15', label: 'Course Work 15' },
]

export const ASSESSMENT_TYPES: AssessmentType[] = [
  { id: '1', label: 'Article' },
  { id: '2', label: 'Assignment' },
  { id: '3', label: 'Assignment 1' },
  { id: '4', label: 'Assignment 2' },
  { id: '5', label: 'Assignment 3' },
  { id: '6', label: 'Assignment 4' },
  { id: '74', label: 'Assignment 5' },
  { id: '75', label: 'Assignment 6' },
  { id: '76', label: 'Assignment 7' },
  { id: '69', label: 'Attendance' },
  { id: '85', label: 'CAD' },
  { id: '8', label: 'Case Study' },
  { id: '7', label: 'Class Assignment' },
  { id: '47', label: 'Class Test 1' },
  { id: '48', label: 'Class Test 2' },
  { id: '61', label: 'Class Test 3' },
  { id: '94', label: 'ColorProcessing' },
  { id: '97', label: 'Company Assessment' },
  { id: '71', label: 'Creativity & Design Aesthetic' },
  { id: '96', label: 'CreativityandComposition' },
  { id: '92', label: 'Data Analysis' },
  { id: '100', label: 'Dissertation' },
  { id: '84', label: 'Drawing' },
  { id: '9', label: 'Essay Writing' },
  { id: '11', label: 'Exercise 1' },
  { id: '12', label: 'Exercise 2' },
  { id: '13', label: 'Exercise 3' },
  { id: '14', label: 'Exercise 4' },
  { id: '15', label: 'Exercise 5' },
  { id: '16', label: 'Exercise 6' },
  { id: '10', label: 'Exercises' },
  { id: '87', label: 'Extra Mark' },
  { id: '17', label: 'Final Exam' },
  { id: '78', label: 'Final Film' },
  { id: '18', label: 'Final Project' },
  { id: '19', label: 'Final Report' },
  { id: '20', label: 'Group Assignment' },
  { id: '21', label: 'Group Assignment 1' },
  { id: '22', label: 'Group Assignment 2' },
  { id: '24', label: 'Group Presentation' },
  { id: '23', label: 'Group Project' },
  { id: '25', label: 'Journal' },
  { id: '26', label: 'Lab Test 1' },
  { id: '27', label: 'Lab Test 2' },
  { id: '28', label: 'Literature Review' },
  { id: '99', label: 'Log Book' },
  { id: '29', label: 'Mid-Term Test' },
  { id: '83', label: 'Mock Up Study' },
  { id: '73', label: 'Neatness' },
  { id: '72', label: 'Originality' },
  { id: '37', label: 'Participation' },
  { id: '95', label: 'PhotoManipulation' },
  { id: '86', label: 'Preliminary Model & Rapid Prototype' },
  { id: '36', label: 'Presentation' },
  { id: '60', label: 'Presentation 1' },
  { id: '62', label: 'Presentation 2' },
  { id: '64', label: 'Presentation 3' },
  { id: '91', label: 'Primary Research' },
  { id: '89', label: 'Progression' },
  { id: '31', label: 'Project' },
  { id: '32', label: 'Project 1' },
  { id: '33', label: 'Project 2' },
  { id: '34', label: 'Project 3' },
  { id: '35', label: 'Proposal' },
  { id: '81', label: 'Public Service Announcement' },
  { id: '30', label: 'Public Speaking' },
  { id: '90', label: 'Qualitative and Quantitative Research' },
  { id: '39', label: 'Quiz 1' },
  { id: '40', label: 'Quiz 2' },
  { id: '41', label: 'Quiz 3' },
  { id: '42', label: 'Quiz 4' },
  { id: '43', label: 'Quiz 5' },
  { id: '38', label: 'Quizzes' },
  { id: '93', label: 'Referencing and Citations' },
  { id: '98', label: 'Report' },
  { id: '44', label: 'Report Writing' },
  { id: '77', label: 'Script' },
  { id: '46', label: 'Seminar' },
  { id: '79', label: 'Short Film' },
  { id: '65', label: 'Speech' },
  { id: '66', label: 'Speech 1' },
  { id: '67', label: 'Speech 2' },
  { id: '68', label: 'Speech 3' },
  { id: '45', label: 'Supervisor Contribution' },
  { id: '88', label: 'System Demonstration' },
  { id: '70', label: 'Technical Skills' },
  { id: '80', label: 'Treatment' },
  { id: '49', label: 'Tutorial 1' },
  { id: '57', label: 'Tutorial 10' },
  { id: '50', label: 'Tutorial 2' },
  { id: '51', label: 'Tutorial 3' },
  { id: '52', label: 'Tutorial 4' },
  { id: '53', label: 'Tutorial 5' },
  { id: '54', label: 'Tutorial 6' },
  { id: '55', label: 'Tutorial 7' },
  { id: '56', label: 'Tutorial 8' },
  { id: '63', label: 'Tutorial 9' },
  { id: '58', label: 'Tutorials' },
  { id: '82', label: 'TV Commercial' },
  { id: '59', label: 'Workshop' },
]